remove_classes = ["paint_feather_strip_residue","fastner_missing","sealant","electrical_tape"]
clean_classes = [
"revit_head_damage"
]

# quality_classes = ['sratch_mark','dent','revit_head_damage','sealant_gap']
quality_classes = ['label_good' 'label_bad']

# micro_classes=['bur','burr','burr_dust','burr_waste','black-mark',
# 'black_dust','black_mark','black_mark_doubt','bristle',
# 'bristle_primer','broken_chips','_excess_sealant_primer',
# 'adhesive_drop','dust','excess_gum_residue',
# 'excess_paint','excess_prime','excess_primer',
# 'excess_primer_blob','excess_primer_burr',
# 'excess_primer_drop','excess_primer_on_bonding_surface',
# 'excess_primier','excess_sealant','excess_sealant_primer',
# 'excess_sealant_residue','excess_selanat_primer',
# 'loose_broken_sealant','loose_sealant','loose_sealant_residue',
# 'masking_sealant','no_paint','paint_pee_off','paint_burr','paint_mark',
# 'paint_marks','primer_blob','primer_bristle','primer_drop','primer_on_bonding_surface',
# 'primer_peel','primer_peel_off','primer_sealant','red_mark','residual','residue',
# 'saelant_mark','scratch','scratch_mark','sealant_dust',
# 'sealant_residue','sealnt_residue','selant_on_fillet','sealant_mark',
# 'sealant_overflow','sealant_primer','sealant_primer_dust','snap_mark',
# 'tape_paste_residue','tape_residue','wast_dust','waste','waste_dust',
# 'waste_paper_residue','waste_residual','waste_residue','stick','hair','paint_peel_off',
# 'piant_peel','paint_peel','peel_off','insect','thread','thread_residue','surface_dirt',
# 'ink_mark','line_mark','gum_residue','paint_strip_residue',"orange_tape_residue",'paint_residue','paint_residue_revit',
# 'orange_tape_residue','orange_tape_residuew',"white_paste","wood_piece"]
macro_classes = ["nothing"]
# macro_classes = ['Pg_drill_gun','Surgery_knife','air_blower','alen_key','torch',
# 'brush_cap','atm_card','book','bottle','aluminium_metal_residue',
# 'aluminium_sheet','aluminium_tape','aluminium_tape_residue','aluminum_tape',
# 'aluminum_tape_residue','belt','belt_sander','broken_filler_gauge',
# 'broken_filler_guage','broken_stem','broken_zip_tag','broken_zip_tie',
# 'brown_paper','brush','bu','bubble_sheet','buck_tail','buckingbar',
# 'bursh_cap','capative_screw_installation_tool','carry_forward_tag',
# 'cello_tape','chip_chaser','chuck_key','cleco_plier','clico','cloth','coin',
# 'cold_working_tool','critical_area_floor_masking_tape','critical_area_floor_masking_tape_residue',
# 'csk_drill_bit','csk_micro_stopper','currency_note','diary','drill_bit','drill_bitd','drill_gun','drill_handle',
# 'drill_stop','duct_cap','ear_phone','ear_plug','ear_plug_rope',
# 'edge_deburring_tool','ejector_pin','electric_tape','electrical_primer_drop',
# 'electrical_tape','electrical_tape_residue','emery_sheet','fastner_missing',
# 'filler_gauge','flat_driver','flat_file','floor_masking_tape','floor_masking_tape_residue',
# 'foam','foam_bed','foam_cover','foam_piece','foam_sheet','fod_bag','fod_high_lock_collar',
# 'gloves','goggle','goggles','green_tape','hair_primer',
# 'hand_kerchief','hand_sqeezer','handle','headset','high_lock_collar',
# 'hilok_removal_tool','hole_deburring_tool','hole_filler_bud','hole_filler_buds',
# 'hole_picker','id_card','id_card_tag','identification_tag',
# 'instrument_kit_bag','jiffy_gun','k69_kaizen_tool','key','key_chain','knife',
# 'laptop','leaf','light','mask','masking_tape','masking_tape_residual',
# 'masking_tape_residue','mirror','mis_engg','mobile_phone','ms_engg_file','nc_tag',
# 'nose_piece','notebook',
# 'nut_plate_jig','nut_plate_masking_plug','orange_tape','orange_tape-residue',
# 'orange_tape_roll','paint_brush',
# 'paper','pen','pen_mark','pencil','pencil_grinder','permission_card',
# 'plastic_cover','power_cleco_gun','prick_punch','primer_cup','ratchet',
# 'reamer_drill_bit','red_tape','retainer_spring','rf_id','ring','rivet','rivet_cutter',
# 'rivet_driver','rivet_gun','rivet_head','rivet_head_driver','rivet_snap','rivet_tape',
# 'rope','round_file','screw','sealant_cup','sealant_gun','shoe','silver_tape',
# 'snipper','socket','socks','solid_fastner_screw','spanar','spectacles','stem',
# 'stone','surgical_knife','tape','tape_roll',
# 'tissue_paper','tool_mark','transparent_tape','tray','universal_head_driver','vaccum_blower',
# 'vernier','vernier_caliper','vinial_tape','visiting_card',
# 'visitor_card','wallet','washer','water_bottle','white_paper_piece','wire_locking_plier','wrench']